name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            resume.typ
            resume_es.typ

      - name: Rename PDF
        run: mv resume.pdf Juan_Bautista_Zunino_Resume.pdf
        run: mv resume_es.pdf Juan_Bautista_Zunino_Resume_es.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Update latest tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: latest

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "${{ env.DATE }}"
          files: |
            Juan_Bautista_Zunino_Resume.pdf
            Juan_Bautista_Zunino_Resume_es.pdf
